export { default as Navbar  } from './Navbar/Navbar';
export { default as Banner  } from './Banner/Banner';
export { default as About   } from './About/About';
export { default as Work    } from './Work/Work';
export { default as Help    } from './Help/Help';
export { default as Pricing } from './Pricing/Pricing';
export { default as Reviews } from './Reviews/Reviews';
export { default as Footer  } from './Footer/Footer';
export { default as Order   } from './Order/Order';